version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      # Test Build (Dockerfile.dev)
      #- echo Build started on `date`
      #- echo Building Docker test image...
      #- docker build -t $IMAGE_REPO_NAME:$TEST_IMAGE_TAG -f Dockerfile.dev .
      #- docker run -e CI=true $IMAGE_REPO_NAME:$TEST_IMAGE_TAG npm run test
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose --file=docker-compose-prod.yml build
  post_build:
    commands:
      # replace env vars in Dockerrun.aws.json
      - sed -i 's/${AWS_ACCOUNT_ID}/'"$AWS_ACCOUNT_ID"'/g; s/${AWS_REGION}/'"$AWS_REGION"'/g; s/${APPLICATION_NAME}/'"$APPLICATION_NAME"'/g' 'Dockerrun.aws.json'
      # push container to ECR
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose --file=docker-compose-prod.yml push
artifacts:
  files:
    - 'Dockerrun.aws.json'
