version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: n 14
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '.nuxt/**/*'
    - 'package.json'
    - 'node_modules/**/*'
