version: '3'

services:
  nuxt:
    build: ./app
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APPLICATION_NAME}-nuxt
    container_name: nuxt-app
    ports:
      - '3000:3000'
    command: 'npm run start'

  nginx:
    build: ./nginx
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APPLICATION_NAME}-nginx
    container_name: nginx-server
    ports:
      - '80:80'
    depends_on:
      - nuxt
