version: '3'

services:
  nuxt:
    build: ./app
    container_name: nuxt-app
    ports:
      - '3000:3000'
    command: 'npm run start'

  nginx:
    build: ./nginx
    container_name: nginx-server
    ports:
      - '80:80'
    depends_on:
      - nuxt
